module.exports = {
  purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    colors: {
      transparent: 'transparent',
      mono: {
        black: '#333',
        blackHover: '#666',
        blackActive: '#808080',
        paleBlack: '#666',
        paleBlackHover: '#808080',
        paleBlackActive: '#999',
        darkGray: '#999',
        darkGrayHover: '#777',
        darkGrayActive: '#666',
        gray: '#CCC',
        grayHover: '#e6e6e6',
        grayActive: '#f2f2f2',
        lightGray: '#DDD',
        lightGrayHover: '#ccc',
        lightGrayActive: '#b3b3b3',
        pale: '#eee',
        paleHover: '#d9d9d9',
        paleActive: '#bfbfbf',
        paleWhite: '#f7f7f7',
        paleWhiteHover: '#e6e6e6',
        paleWhiteActive: '#ccc',
        white: '#fff',
        whiteHover: '#f2f2f2',
        whiteActive: '#d9d9d9',
      },
      main: {
        red: '#F85A5E',
        redHover: '#fa8589',
        redActive: '#fcb6b8',
        blue: '#3067A8',
        blueHover: '#3878c7',
        blueActive: '#6093d2',
        navy: '#001B57',
        navyHover: '#002880',
        navyActive: '#0039b3',
        darkNavy: '#1F2940',
        darkNavyHover: '#293756',
        darkNavyActive: '#3a4d78',
        yellow: '#F7C954',
        yellowHover: '#f9d885',
        yellowActive: '#fce8b6',
        turquoise: '#5EBCCA',
        turquoiseHover: '#79c6d2',
        turquoiseActive: '#9fd7df',
        pink: '#F97F90',
        pinkHover: '#fa9eaa',
        pinkActive: '#fdced4',
      },
      sub: {
        babyPink: '#FEDDDF',
        babyPinkHover: '#fdb5ba',
        babyPinkActive: '#fb838b',
        green: '#92DCA9',
        greenHover: '#78d395',
        greenActive: '#52c777',
        sky: '#58C5E3',
        skyHover: '#3bbade',
        skyActive: '#21a1c4',
        darkPurple: '#6258BA',
        darkPurpleHover: '#776ec4',
        darkPurpleActive: '#9992d3',
        paleYellow: '#EABF80',
        paleYellowHover: '#f1d3a7',
        paleYellowActive: '#f8e9d3',
        purple: '#B48BD3',
        purpleHover: '#c3a3dc',
        purpleActive: '#dbc8ea',
        lightGreen: '#BBDA85',
        lightGreenHover: '#c8e19d',
        lightGreenActive: '#deedc4',
        paleBlue: '#A3B7ED',
        paleBlueHover: '#bfcdf2',
        paleBlueActive: '#eaeefb',
        ocean: '#99EAED',
        oceanHover: '#bef2f4',
        oceanActive: '#e9fbfb',
        pink: '#EF91AA',
        pinkHover: '#f5bccb',
        pinkActive: '#fce9ee',
        darkNavy: '#233148',
        darkNavyHover: '#324667',
        darkNavyActive: '#425e8a',
        lightBlue: '#4695EC',
        lightBlueHover: '#75b0f0',
        lightBlueActive: '#a3cbf5',
        paleSky: '#7FB2D6',
        paleSkyHover: '#9fc5e0',
        paleSkyActive: '#c5dcec',
        lightYellow: '#FFEC36',
        lightYellowHover: '#fff066',
        lightYellowActive: '#fff599',
      },
      sns: {
        naver: '#2AB404',
        naverHover: '#34e105',
        naverActive: '#4efa1e',
        facebook: '#3B599B',
        facebookHover: '#466ab9',
        facebookActive: '#6b88c7',
        kakao: '#F7E106',
        kakaoHover: '#faea38',
        kakaoActive: '#fbef6a',
        google: '#DA2915',
        googleHover: '#ea412e',
        googleActive: '#ef6b5d',
        apple: '#222',
        appleHover: '#333',
        appleActive: '#4d4d4d',
        other: '#737373',
        otherHover: '#8c8c8c',
        otherActive: '#a6a6a6',
      },
    },
    fontSize: {
      titleMassive: ['2rem', { lineHeight: '1.8rem' }],
      titleBig: ['1.5rem', { lineHeight: '1.25rem' }],
      titleMedium: ['1.25rem', { lineHeight: '1.2rem' }],
      titleSmall: ['1.25rem', { lineHeight: '1.2rem' }],
      subTitleBig: ['1.125rem', { lineHeight: '1.1rem' }],
      subTitleMedium: ['1rem', { lineHeight: '1rem' }],
      subTitleSmall: ['1rem', { lineHeight: '1rem' }],
      textBig: ['0.875rem', { lineHeight: '0.85rem' }],
      textMedium: ['0.875rem', { lineHeight: '0.85rem' }],
      textSmall: ['0.875rem', { lineHeight: '0.85rem' }],
      subBig: ['0.875rem', { lineHeight: '0.85em' }],
      subMedium: ['0.75rem', { lineHeight: '0.7rem' }],
      subSmall: ['0.625rem', { lineHeight: '0.6rem' }],
    },
    fontWeight: {
      titleMassive: '900',
      titleBig: '900',
      titleMedium: '800',
      titleSmall: '700',
      subTitleBig: '900',
      subTitleMedium: '800',
      subTitleSmall: '500',
      textBig: '900',
      textMedium: '700',
      textSmall: '500',
      subBig: '700',
      subMedium: '500',
      subSmall: '500',
    },
    extend: {
      spacing: {
        neg11: '-11rem',
        neg13: '-13rem',
        0.1: '0.25rem',
        2.3: '0.6rem',
        4.3: '1.125rem',
        4.5: '1.188rem',
        5.5: '1.375rem',
        7.5: '1.875rem',
        8.5: '2.125rem',
        9.5: '2.375rem',
        12.5: '3.125rem',
        13: '3.25rem',
        15: '3.625rem',
        15.5: '3.75rem',
        17: '4.6rem',
        20.5: '5.25rem',
        21: '5.75rem',
        px59: '59px',
      },
      borderWidth: {
        0.5: '0.5px',
      },
      minWidth: {
        60: '3.75rem',
        70: '4.375rem',
      },
      width: () => ({
        fit: 'fit-content',
      }),
      minWidth: () => ({
        fit: 'fit-content',
      }),
      zIndex: {
        max: '900',
      },
      boxShadow: {
        glow: '0 0 4px 1.5px #DDD',
      },
      opacity: {
        85: '0.85',
      },
    },
  },
  variants: {
    extend: {
      backgroundColor: ['hover', 'active'],
      backgroundOpacity: ['hover', 'active'],
      borderColor: ['hover', 'active'],
      borderOpacity: ['hover', 'active'],
      boxShadow: ['hover', 'active'],
      gradientColorStops: ['hover', 'active'],
      opacity: ['hover', 'active'],
      outline: ['hover', 'active'],
      placeholderColor: ['hover', 'active'],
      placeholderOpacity: ['hover', 'active'],
      ringColor: ['hover', 'active'],
      ringOffsetColor: ['hover', 'active'],
      ringOffsetWidth: ['hover', 'active'],
      ringOpacity: ['hover', 'active'],
      ringWidth: ['hover', 'active'],
      rotate: ['hover', 'active'],
      scale: ['hover', 'active'],
      skew: ['hover', 'active'],
      textColor: ['hover', 'active'],
      textDecoration: ['hover', 'active'],
      textOpacity: ['hover', 'active'],
      translate: ['hover', 'active'],
      zIndex: ['hover', 'active'],
    },
  },
  plugins: [],
}
